'use strict';
const COMPONENTS_ADD = 'COMPONENTS_ADD';
const COMPONENTS_SELECT = 'COMPONENTS_SELECT';
const STYLE_INIT = 'STYLE_INIT';
const STYLE_UPDATE = 'STYLE_UPDATE';
module.exports = {
  COMPONENTS_ADD,
  COMPONENTS_SELECT,
  STYLE_INIT,
  STYLE_UPDATE
};
